### PR TITLE
JENKINS-55439 - Update remoting to the latest version

### PR DESCRIPTION
**Pull request by fnaum**
Jenkins master disconnects the nodes if it detects that the remoting version is old
This one line change is to be able to compile against the latest version of remoting (3.29)

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
We can merge with squash to remove reverted commits

**Comment by fnaum** [comment]
Yes, sorry, I should have clean them before submitting the PR, there are some changes needed because we are behind a firewall

**Comment by oleg-nenashev** [comment]
Just testing the Gitter webhook ...

**Comment by pvtuan10** [comment]
LGTM. Thanks for the contribution!

**Pull request merged**
