### PR TITLE
Incrementals

### PR DESCRIPTION
**Pull request by casz**
incremental artifacts show that plugin-pom is fully capable of JAR packing.

### CODE REVIEW

**Comment by casz** [comment]
sadly the current POM setup excludes incrementals then as I see it.

**Comment by casz** [comment]
@oleg-nenashev created https://github.com/jenkinsci/incrementals-tools/pull/8

**Comment by jglick** [comment]
> the current POM setup excludes incrementals then

No, `org.jenkins-ci:jenkins` supports Incrementals. Jenkins core uses this. This PR needs to be fixed, but why was it closed?

**Comment by casz** [comment]
Waiting for https://github.com/jenkinsci/incrementals-tools/pull/8 to use incrementilfy 👍 then I will reopen 😄

**Pull request closed without merging**
